name: Publish Python Package

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish distribution to DroneBase-ML Private PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: ${{ secrets.PRIVATE_PYPI_USER }}
        password: ${{ secrets.PRIVATE_PYPI_PSWD }}
        repository_url: ${{ secrets.PRIVATE_PYPI_REPO }}